apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-conf-volume
  annotations:
      volume.beta.kubernetes.io/storage-class: "che-conf"
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
     path: /nfsvolumes/pv0001

