apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-workspace-volume
  annotations:
      volume.beta.kubernetes.io/storage-class: "che-workspace"
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
     path: /nfsvolumes/workspaces

