kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-che-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "che-data"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
