kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-che-conf
  annotations:
      volume.beta.kubernetes.io/storage-class: "che-conf"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
